linters:
  enable-all: false
  enable:
    - golint
    - gosimple
    - misspell
    - gocyclo
    - gofmt
    - structcheck
    - varcheck
    - ineffassign
    - typecheck
    - megacheck
    - deadcode
    - govet
    - errcheck
    - goimports
    - depguard
    - goconst
    - unconvert
    - gocritic

linters-settings:
  depguard:
    list-type: whitelist
    packages:
      - github.com/mmcloughlin/avo
      - golang.org/x/
